# Generated by Django 5.2 on 2025-04-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Puesto')),
                ('company', models.CharField(max_length=255, verbose_name='Empresa')),
                ('company_valuation', models.FloatField(blank=True, null=True, verbose_name='Valoración de la empresa')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('contract_type', models.CharField(max_length=100, verbose_name='Tipo de contrato')),
                ('salary', models.CharField(max_length=100, verbose_name='Salario')),
                ('min_exp', models.CharField(max_length=100, verbose_name='Experiencia mínima')),
                ('url', models.URLField(verbose_name='URL de la oferta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Oferta de trabajo',
                'verbose_name_plural': 'Ofertas de trabajo',
                'ordering': ['-created_at'],
            },
        ),
    ]
