# Generated by Django 5.2 on 2025-04-10 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('url', models.URLField(verbose_name='URL de la oferta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='Salario')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('source', models.CharField(max_length=50, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('search_keywords', models.CharField(max_length=200, verbose_name='Palabras clave de búsqueda')),
                ('search_location', models.CharField(max_length=100, verbose_name='Ubicación de búsqueda')),
            ],
            options={
                'verbose_name': 'Oferta de trabajo',
                'verbose_name_plural': 'Ofertas de trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=200, verbose_name='Palabras clave')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('source', models.CharField(max_length=50, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de búsqueda')),
                ('results_count', models.IntegerField(default=0, verbose_name='Número de resultados')),
            ],
            options={
                'verbose_name': 'Historial de búsqueda',
                'verbose_name_plural': 'Historial de búsquedas',
                'ordering': ['-created_at'],
            },
        ),
    ]
