# Generated by Django 5.2 on 2025-04-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='published_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fecha de publicación'),
        ),
    ]
