# Generated by Django 5.2 on 2025-04-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Beneficios sociales'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='category',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='conditions',
            field=models.TextField(blank=True, verbose_name='Condiciones'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='functions',
            field=models.TextField(blank=True, verbose_name='Funciones'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='industry',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Tipo de industria'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='level',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='vacancies',
            field=models.IntegerField(default=1, verbose_name='Vacantes'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='work_mode',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Modalidad de trabajo'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.CharField(max_length=200, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company_valuation',
            field=models.FloatField(blank=True, null=True, verbose_name='Valoración empresa'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='country',
            field=models.CharField(default='España', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
