# Generated by Django 5.2 on 2025-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joboffer_benefits_joboffer_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='applicants',
            field=models.IntegerField(default=0, verbose_name='Inscritos'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='min_education',
            field=models.CharField(default='N/A', max_length=200, verbose_name='Estudios mínimos'),
        ),
    ]
