# Generated by Django 5.2 on 2025-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joboffer_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de contrato'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='min_experience',
            field=models.CharField(blank=True, max_length=100, verbose_name='Experiencia mínima'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='work_mode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modo de trabajo'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='published_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fecha de publicación'),
        ),
    ]
