# Generated by Django 5.2 on 2025-04-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_joboffer_contract_type_joboffer_min_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='search_keywords',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='search_location',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='source',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='languages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='search_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='jobs.searchhistory'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='studies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='min_experience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='work_mode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
