# Generated by Django 5.2 on 2025-04-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_joboffer_options_remove_joboffer_is_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='inscritos',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de inscritos'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='vacantes',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de vacantes'),
        ),
    ]
