# Generated by Django 5.2 on 2025-04-14 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_joboffer_inscritos_joboffer_vacantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='publication_date',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
